baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Passengers Blog'


[params]
    description = "the fastest blog"
    dateFormat = "Jan 2,2006"
[taxonomies]
    author = "authors"
    category = "categories"